### ISSUE TITLE
Chat attendee list doesn't scroll under Safari

### ISSUE THREAD

**Issue by freakboy3742** [venueless/venueless#103]
Under Safari (13.1.2 (15609.3.5.1.3) on Catalina), the list of participants in a chat room doesn't appear as a scrolled box. Instead, it's a fixed height box, with all participants spaced evenly inside that box. This means the names themselves are unreadable once you have a large number of participants.

The box renders fine on Chrome on Catalina.

Observed in the PyConline AU event rooms.

I have screenshots, available on request; I won't post them publicly because of potential privacy issues.

**Comment by rashfael** [comment]
Fixed by https://github.com/venueless/venueless/commit/f2e22a7cc9616cdda5e6ce4e2a722d1107382f45 , thanks for the report!
