### ISSUE TITLE
Landing page room is always "active"

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#109]
So this one is a really really small bug. The room that maps to the ``/`` URL always shows darker than all other rooms, regardless of whether it is a page (didn't check that one), stage, or channel.

![2020-09-04-031756_348x327_scrot](https://user-images.githubusercontent.com/64280/92188580-4712b900-ee5d-11ea-83bb-9f6f7e6c87c9.png)

**Comment by rashfael** [comment]
looks like we need to use `exact-active` not `active` as the class to style from vue-router
