### ISSUE TITLE
White-on-transparent video buttons are impossible to locate on white backgrounds

### ISSUE THREAD

**Issue by yaakov-h** [venueless/venueless#115]
On this holding slide from pyconlineau, the mute and video quality selector buttons are effectively invisible.

This is on a narrow window (~960px wide) on desktop, which flips the webapp into the mobile view.

![image](https://user-images.githubusercontent.com/426009/92201024-bb317900-eebe-11ea-943b-2e816f638f07.png)

**Comment by rixx** [comment]
Thank you for pointing that out, the fix is under way and will be deployed before the next day of PyCon AU talks starts.
