### ISSUE TITLE
Chat sidebar has problems with wide links in Safari

### ISSUE THREAD

**Issue by freakboy3742** [venueless/venueless#122]
If a user pastes content that exceeds the width of the chat bar, the rendering of the chat bar is expanded to the width of the link - but the left of the screen runs under the video window: 

<img width="696" alt="Screen Shot 2020-09-05 at 10 09 26 am" src="https://user-images.githubusercontent.com/37345/92295218-eae48d80-ef5f-11ea-990f-dd4a002fb30d.png">

This persists until the long link disappears from the chat history.

It can't be fixed by making the window wider; the layout expands the video, but not the chat window; and I can't see any control to widen the chat at the expense of the video.

Long links seem to work fine for Chrome.

**Comment by rixx** [comment]
Thanks for reporting this! We'll try to get a fix in before PyCon AU sprints tomorrow, as we'd like to avoid deploying updates between talks if at all possible.
