### ISSUE TITLE
LQ/MQ/HQ for streams without height attribute

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#126]
The new level chooser chooses to show LQ/MQ/HQ based on the height of the video. If the HLS metadata does not contain the resolution, it always renders LQ.

This is really bad, since our nginx setup does not contain the resolution and there *will* be customer complaints of why our setup always is LQ ;)

Option A) We just assign HQ to the highest available level, LQ to the lowest, and MQ to everything else?

Option B) We just display "Auto" in the icon

**Comment by rashfael** [comment]
we could parse bitrate as fallback, that should always be available.

**Comment by raphaelm** [comment]
faking the resolution doesn't sound good.

I will try if we can just set ``RESOLUTION=XxY`` in our nginx config as part of [hls_variant](https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls_variant) but some fallback would be nice

**Comment by raphaelm** [comment]
> I will try if we can just set RESOLUTION=XxY in our nginx config as part of hls_variant but some fallback would be nice

Yup, that worked! Our sample stream now reports 360p, 540p and 720p correctly. :) So this issue still persists for other HLS sources, but with **really low priority** and we could even consider marking it wontfix if we say it's easy enough to fix the HLS source instead.

**Comment by rixx** [comment]
I'm voting to mark *wontfix* and reopen when it turns into an issue again, for better feature-wrangling.
