### ISSUE TITLE
Feature request: pop-out chat

### ISSUE THREAD

**Issue by rixx** [venueless/venueless#129]
Particularly for organisers and moderators, and possibly speakers, it would be useful to be able to see only the chat for a room.

Bonus points if we can still display the ongoing reactions, but rash will probably veto that.

Related work: Twitch offers this for streamers at `/…/chat`

**Comment by coderanger** [comment]
Bonus bonus points: if it is iframe-able for a hacky multi-channel view.

**Comment by awlx** [comment]
This feature also would be awesome for people who stream the conference via Airplay/Chromecast to their TV. Because otherwise you have to join every session twice to also see the chat.

**Comment by rashfael** [comment]
We added support for a pop-out chat to display in things like obs and added a organizer/speaker view where you see chat/polls/questions all at once. Chat-only for attendees is a different feature than pop-out chat, but we're working on Hybrid Events #304 which will inlcude stuff like that.
