### ISSUE TITLE
Feature: multiple stream sources per room

### ISSUE THREAD

**Issue by rixx** [venueless/venueless#130]
At PyConline AU we had backup streams, which would have liked to share the same chat across the streams.

This is *technically* possible for us, we just have to decide if we want to allow organisers to configure this and expose that as a feature. Shared chatrooms across streams seem, to me, have a limited-but-possible usecase.

**Comment by raphaelm** [comment]
Shared chats would be possible, but I think a different solution to the problem allows even more flexibility: Multiple stream sources per room ;)

Just as we now have a quality selection, we could have a stream source selection. This would not only solve the "backup stream" use case in a way that's arguably even more clean, but it also solves the use case of multi-language streams where the client isn't able to send a multi-sound-track stream input, but instead can provide multiple streams. (Arguably, for translated streams it might make sense to split up the chats by chat language, but it also might not if most people understand one language in writing, but prefer to listen to a translation for a speedy talk.)

**Comment by raphaelm** [comment]
Implemented in 23d85e1
