### ISSUE TITLE
Allow easy way to embed images in Markdown components

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#146]
We need some way to allow non-technical users to upload images to markdown texts, such as pages or sponsor texts.

Take for example GitHub. There's a "attach files" button above the field, and you can also drag-and-drop images into the field. One of both options would be enough for a start.

When you do, GitHub inserts a 

```
![Uploading $filename…]()
```

which then gets replaced with the actual CDN file name.

**Comment by saschafoerster** [comment]
Also resizing of images should be thought of for the non-technical users, I would recommend from our experience.

**Comment by raphaelm** [comment]
Closed, we no longer use markdown
