### ISSUE TITLE
If room names are to long, the save button is not accessible

### ISSUE THREAD

**Issue by MrGamy** [venueless/venueless#152]
If a room with a long name is created you cannot easily edit the room after creation because the save button will be rendered off screen.
Would it be possible to fix the position of the save button / render it on top of the text?

**Comment by rashfael** [comment]
Since the save button in the room admin view is now on the bottom, this shouldn't be a problem anymore. Secondary actions however are still on top and have been fixed to no longer get pushed off screen.
