### ISSUE TITLE
Attaching images may leak location data

### ISSUE THREAD

**Issue by tsukasa-au** [venueless/venueless#177]
Venueless allows users to upload files/post images in the different rooms. If someone takes a photo with their cell phone, it very likely contains their precise location information stored in the image's exif data.

Most online services automatically (discord, twitter, etc) automatically strip the location information from photos that are posted - as most people do not realise that they are posting their exact physical location with their image.

Can you please start stripping this location information?

**Comment by raphaelm** [comment]
Good point, thanks for the feedback! We currently don't process images at all, which has other perky, but this probably does make sense to change.
