### ISSUE TITLE
SameSite cookie deprecation warning in Firefox

### ISSUE THREAD

**Issue by kurahaupo** [venueless/venueless#178]
Firefox console shows this warning:
> Cookie “muxData” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
> mux.js:7:64833

(This is when viewing `https://lca2021.venueless.events/rooms/*`)

**Comment by raphaelm** [comment]
That cookie isn't set by us, but my mux, which the LCA AV team used for video delivery and video delivery measurements. It's not used for most other Venueless projects and we can't change it.
