### ISSUE TITLE
iFrame module within stage room-type

### ISSUE THREAD

**Issue by MrXermon** [venueless/venueless#216]
We'd like to embed our own live-stream player to deliver a multi-language video-stream as a stage to the audience. We use our own player based on video.js as we've already extended it with a bunch of other features like a option to switch the language of the stream and buttons for AirPlay and Chromecast sharing.
Until some time ago, there was a option to customize the room in some sort of editor and to add more modules like the iFrame or the Q&A module to the room. Is there any chance of getting this options back or add iFrame as another "type" of stage?

**Comment by rashfael** [comment]
We restricted the combination of modules to make it easier to understand room administration and to limit the combinations of modules we need to take into account when desiging the UI. With an iframe + chat/Q&A you are missing out on proper stage features like background playing and reactions.

Our built-in player supports alternative stream sources for multi-language streams and WebVTT subtitles. Chromecasting is currently only supported via the context menu.

Are there other issues blocking you from using the built-in player?

**Comment by rashfael** [comment]
We do support youtube streams, which is just an iframe, so it wouldn't be that big of a leap. Do you have an example url to your player I could test this with?

**Comment by MrXermon** [comment]
Hi @rashfael,

thank you for the feedback. Yeah, there are some more features like WebRTC which we're using from time to time if a lower latency compared to HLS is required and a statistics module which gathers some technical information mainly about the quality on the viewers end (watched quality level, average watchtime of the stream, ...) and pushes it back to our statistics server.
I've dropped a example-stream right here: https://dev.mrxermon.de/streaming/?slug=example-stream
I were able to embed the player without any issue with the normal iFrame module in any other room. In older versions of venueless I played with embedding the iFrame besids the Chat and Q&A Module as well without any issues. I think it would give the users of venueless more options to use alternative streaming services like Twitch etc. which could get handy in some cases. Although I totally understand if you want to reduce the amount of combinations of the modules and therefore stick with the already embedded player because it makes testing and troubleshooting a lot easier.

Have a good one!
Jan

**Comment by rashfael** [comment]
Thanks for the link, I'll test that later today.
The current iframe module `page.iframe` was only intended for static page content, and only accidentially works together with the chat sidebar right now. It also does not register as a real stage, which has more features.
I started a [branch](/venueless/venueless/tree/livestream-iframe-player) where an iframe can be a real stage.

**Comment by rashfael** [comment]
Seems to be generally working, however your player does not seem to like being resized into our picture-in-picture mode and gets stuck loading.

https://user-images.githubusercontent.com/1093590/113356708-ff94d280-9342-11eb-9233-34ff3e87336c.mp4

**Comment by rashfael** [comment]
Handling the iframe with a little more care on our end seems to preserve the stream.

**Comment by MrXermon** [comment]
Cool thing!
Just out of interest, have you tried other players as well? I‘ll see if I find the time today to enroll the dedicated branch in my test machine as well and to have a look on it, too.

**Comment by rashfael** [comment]
We tried both hls.js and shaka as the player engine with our own UI on top. I also had a look at video.js, but it seemed harder to integrate into an existing UI. There doesn't seem to be a clear "best player", we found that every library had problems with certain *different* edge cases and weird hls streams.

**Comment by rashfael** [comment]
Closing this since the iframe player module seems to be working.
