### ISSUE TITLE
Installation process Debian10

### ISSUE THREAD

**Issue by dcastanheira** [venueless/venueless#228]
Hello Master's,

today is my first day with venueless and of course this instalattion process is the biggest chanlenge for me. Now i have the venueless running in debian10. But i cant install the BBB server, and to be honest i cannot find good information over the web for this particular setup, BBB in Debian. Anyone knows a good link abbout this installation and integration with venueless?

Many thanks in advance.

**Comment by raphaelm** [comment]
I'm really sorry, but we do not have the time to provide support for general linux/BBB questions. If someone else wants to reply, feel free to do so, but since this isn't a bug in venueless, I'm closing it for now.

**Comment by dcastanheira** [comment]
Hi again,

since the last time i have some improvments in my installation process. Its almost everything working.

Point of situation

I have 2 different servers for this project. 01 is running Debian10 with Venueless (www.mydomain.pt), and 01 is running ubuntu 18.04 with BBB (bbb.mydomain.pt)

This servers are in same Ip address, because of this and for put everything working i have the BBB server receiving the request's and have a Proxy config to foward the requests to Venueless server
```
server {
    listen 80 default_server;
    listen [::]:80 ipv6only=on default_server;
    server_name www.onlinevenue.pt;
    return 301 https://$host$request_uri;
}
server {
    listen 443;
    listen [::]:443 ;
    server_name www.onlinevenue.pt;

    ssl on;
    ssl_certificate /etc/letsencrypt/live/www.onlinevenue.pt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.onlinevenue.pt/privkey.pem;

    location / {
        proxy_set_header    Host $host;
        proxy_set_header    X-Real-IP $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    X-Forwarded-Ssl on;
        proxy_read_timeout  300s;
        proxy_redirect              http:// https://;
        proxy_pass                  http://192.168.1.112:8002;
    }
}
```
and this part is working well.

After BBB instalation, i have checked all details, and in standalone BBB is working well, videocalls, audio, sharescreen, recordings, chats, etc.
Next
Have tried make the configuration for the BBB server details into Postgresql venueless database
![image](https://user-images.githubusercontent.com/18497806/117155667-df7a8800-adb4-11eb-86ea-1f081a6cc1b6.png)

Now, i have Venueless working, but when i try create a channel or make a videocall in private chat always have something like this,
![image](https://user-images.githubusercontent.com/18497806/117156482-a5f64c80-adb5-11eb-89a0-5fc323dd3593.png)

Anyone have a idea about the cause for this socket closed error?

Many thanks in advance.
