### ISSUE TITLE
alternative stream button won't disappear when removing alternative streams in the admin interface for a room

### ISSUE THREAD

**Issue by MrGamy** [venueless/venueless#246]
When adding an alternative stream to a stage room, a button to switch between the alternatives will appear on stream. This button will not disappear after removing all alternative streams from the room again.

**Comment by rashfael** [comment]
Thanks for the report.
Deleting the last alternative left an empty array in the config. With e69d412 the whole key now gets deleted when the last item is removed.
Additionally, with 1bd2990, we won't show the alternatives icon anymore even if an empty alternatives array is present in the config.
