### ISSUE TITLE
Some UI Content remains unlocalized

### ISSUE THREAD

**Issue by itamargiv** [venueless/venueless#303]
While attending the WikidataCon conference, I noticed that some of the UI still contains unmatched translation keys. See screenshot below for reference. The translation keys noticed are:

* `RoomsSidebar:schedule:label`
* `RoomsSidebar:channels-headline:text`
* `RoomsSidebar:browse-channels-button:label`
* `RoomsSidebar:direct-messages-headline:text`
* `ChatInput:input:placeholder`

_**UPDATE**: Refreshing the page seems to have corrected this issue. Although the messages are now in Portugese, and I believe they were in English before_

![Screenshot from 2021-10-29 15-00-37](https://user-images.githubusercontent.com/6132917/139441381-feb88fb2-17f1-462c-941d-7ea7155352bc.png)

**Comment by raphaelm** [comment]
closing until we see this again
