### ISSUE TITLE
Accessibility: Hamburger menu with letters "Menu"

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#314]
Many users with small screens (and usually little experience in digital events or digital tools) have issues with the hamburger menu. They don't recognize it as a menu-button, so they are stuck on the start page and ask our support-team what to do, they don't see anything. :) 

So, I remember long times ago to have read, that the hamburger menu experience can be much improved by writing "Menu" next to it, I created a screenshot. Our experience tells us, this would help us to reduce support efforts. 

<img width="193" alt="Hamburger-menü mit MENÜ daneben bitte" src="https://user-images.githubusercontent.com/1153741/144463394-32d36848-4299-4c84-b782-7f7e4c5927a7.png">

**Comment by rashfael** [comment]
As part of the larger hybrid-events feature we also plan on doing a redesign of the mobile navigation and I am currently favoring an even clearer approach of adding a botton navigation bar, which will additionally highlight the schedule for easier access.
