### ISSUE TITLE
Cannot connect to redis://127.0.0.1:6379/0: Error 111 connecting to 127.0.0.1:6379. Connection refused..

### ISSUE THREAD

**Issue by timololipop** [venueless/venueless#319]
Hello,

I am currently looking for a solution for my company. In my container I notice that it doesnt connect to redis, running on the same machine and configured like mentioned in the docs. Any idea?

Thanks.

**Comment by raphaelm** [comment]
The docs only describe a docker-based installation with 172.17.0.1 as the docker host's IP, not 127.0.0.1 🤔
