### ISSUE TITLE
Responsive breakpoint 769→1024 is pretty useless

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#32]
We start desktop mode at 769px right now, which is used e.g. on iPad (landscape), many smartphones (Nokia 7.1) landscape, and isn't really useful for stream rooms. (It's somewhat okay for our other rooms). Mobile mode would also be problematic probably on landscape phones, so my suggestion would be to handle the rooms like desktop (stream and chat next to each other), but hide the navigation like on mobile.

![Bildschirmfoto vom 2020-05-25 um 11 49 02](https://user-images.githubusercontent.com/64280/82801531-bd2a7b80-9e7d-11ea-9be2-9587257020bd.png)

**Comment by raphaelm** [comment]
This even affects my Samsung 10" tablet in portrait mode

**Comment by rashfael** [comment]
fixed, relevant breakpoints are now at 1400px.
