### ISSUE TITLE
 Feature Request: port Pretix day-based calendar view to Venueless

### ISSUE THREAD

**Issue by digitalesIch** [venueless/venueless#325]
The [day-based calendar view](https://static.pretix.space/static/pretixeu/blog/20211129-release-450/day.56952236aac0.png) from Pretix would be an ideal layout for an event with many stages in Venueless. From our experience participants have trouble finding stages that are out of view before scrolling horizontal in the current schedule. Scrolling to find sessions that take place later in time seems more intuitive to me than scrolling to find more stages.

**Comment by raphaelm** [comment]
The only difference between the pretix day view and the venueless schedule is a flip of the x and y axis. In Venueless, we decided for rooms on the X axis because there are usually not *that* many rooms.

**Comment by rashfael** [comment]
Venueless will use https://www.npmjs.com/package/@pretalx/schedule soon (via https://github.com/venueless/venueless/pull/331) and we won't write any own schedule views for venueless. If you have suggestions on how to improve pretalx schedules, please open an issue at https://github.com/pretalx/schedule/issues.
