### ISSUE TITLE
No "join chat" button on standalone chats

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#35]
Safari on macOS and iOS

<img width="1436" alt="Screenshot 2020-05-25 at 11 04 55" src="https://user-images.githubusercontent.com/64280/82802281-e7306d80-9e7e-11ea-8e3d-eda5934633e3.png">

**Comment by rashfael** [comment]
fixed by https://github.com/venueless/venueless/commit/f2f31b452275a4a59e333c52d9c397fca4b3a0e8
