### ISSUE TITLE
building webapp for production takes very long

### ISSUE THREAD

**Issue by cherbst** [venueless/venueless#353]
The `vue-cli-service build` command takes approx. ~30minutes. During this the node process uses 100% cpu. Is this a known problem? Is there a solution?

**Comment by rashfael** [comment]
Yes, this is quite annoying and mostly down to pdf.js, which is huge, only publishing "modern" syntax releases, which our build chain has to transpile every time. Options are:
- Vendor in a pre-compiled pdf.js in the repo
- find or create a npm package which prebuilts pdf.js
- move to vite, which should have no problem with modern syntax
- upgrade vue-cli to the new major version which just came out, which should also handle modern syntax better

**Comment by raphaelm** [comment]
There seems to be a "legacy browsers" build for pdfjs, at leat on: https://mozilla.github.io/pdf.js/getting_started/

Not sure if that's accessible through NPM in any way, though. Is the "modern syntax" actually unsupported by the browsers we support with venueless or could we just "not transpile" it? Looking at [pdf.js FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support) we should be fine with the regular build already?

**Comment by rashfael** [comment]
Our current build chain can't pass through modern syntax without exploding.

**Comment by raphaelm** [comment]
Meh. Then I don't really want to comment on which of the four solutions is best, you probably have a way better idea what is reasonable here. From my point of view,  option 1 or 2 sounds like quick and easy fixes and 3 or 4 good long-term solutions?

**Comment by rashfael** [comment]
I changed the way pdfjs gets loaded, which makes the build way, way faster.
