### ISSUE TITLE
[Feature Request] Ideas for modules

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#48]
Right now there are three modules in Venueless: 
- native chat
- livestream
- BigBlueButton. 

I would like to collect some other ideas for modules, that could be valuable for the communities using venueless: 
- Jitsi Meet (is far easier to install than BigBlueButton, but also has less features)
- YouTube/Vimeo (collectivly watching prerecorded sessions at the same time with auto-start)
- Websites (any): This could be useful for Social-Media-Walls (#47) but also help as a general purpose module. 
- Moodle and/or H5P: https://h5p.org I am not really shure, how to integrate this well. But Moodle, especially H5P would allow to integrate venueless events with a Learning-Management-System and to integrate tons of interactive features like quizzes (for the pub-quiz-session at the end of the day for instance) 

I hope this is the right place for this ideas, if not, please close, I will put them to the right place.

**Comment by raphaelm** [comment]
Jitsi Meet is not planned, unless there are some big changes in the Jitsi vs BBB landscape.

YouTube/Vimeo and Websites are on our internal roadmap.

H5P/Moodle feels out of scope, these are probably features we'd implement ourselves in Venueless if we'd want them.
