### ISSUE TITLE
[UX] Long titles for rooms don't break well

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#49]
When creating longer room titles, they overlap the following room name. 
<img width="304" alt="Venueless Long Room Name" src="https://user-images.githubusercontent.com/1153741/83968816-14900900-a8cc-11ea-8f8e-cdf30ce3f6f4.png">

**Comment by rashfael** [comment]
fixed in a7411a5c91f3fe4124716f0940d7946c3ee4316b
