### ISSUE TITLE
[Feature Request] RTMP Multistream: Livestream to different external platforms

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#52]
It would be useful if some livestreams could be sent directly to venueless (via RTMP), but then be restreamed to Facebook, Twitter (Periscope), YouTube and/or other RTMP-services. Of course there are plenty of restream-services out there, but an integrated solution in Venueless could be (of course) better integrated and maybe also be part of the business model of Venueless as a premium package. 

For our events it would help to let more people participate, but in external channels they can only participate passively in certain parts of the event, so they are maybe more interested to buy a ticket so they can interact with everyone "behind the scenes" in Venueless.

Multistreaming can relatively easily be created with the nginx-rtmp-module, that is open source. At the same time it could also create recordings. I am not a developer but of course I would love to help test and continue developing this ideas. 

Useful links: 
https://community.jitsi.org/t/stream-to-any-or-multiple-rtmp-destinations-record-simultaneously/51943
https://github.com/michaelkamprath/multi-service-rtmp-broadcaster
https://www.scaleway.com/en/docs/setup-rtmp-streaming-server/
https://openstreamingplatform.com

**Comment by raphaelm** [comment]
This is out of scope for venueless. We're happy to set this up for our customers at additional cost if they need it and we handle the RTMP/HLS streaming, but it's not something that belongs inside venueless.

**Comment by saschafoerster** [comment]
Okay, I also missed nginx-rtmp in the mix of issue #7. Are there reasons?

**Comment by raphaelm** [comment]
Yeah, because it's what we already use if we host streams for people. But venueless does not care where the HLS stream comes from. #7 is about gathering technical approaches to integrate an *end-to-end* streaming solution, i.e. from camera capture to HLS output.
