### ISSUE TITLE
Allow avatar upload

### ISSUE THREAD

**Issue by EdJoPaTo** [venueless/venueless#55]
I would like to have an avatar by url besides the gravatar option as I personally prefer not to use gravatar.
This way there is no need to store images but only an url just like the email address which is used for gravatar.

**Comment by rashfael** [comment]
We will support user uploaded media at some point.
I would like to avoid hotlinking media/images, as many of our users are very privacy-aware. We should limit assets from 3rd party sites to an absolute minimum.

**Comment by EdJoPaTo** [comment]
Fair point. Which is exactly why I have blocked gravatar.
Personally I would prefer loading images from deventral points (a user might have his own url source) but dont like third party centralized sources like gravatar which are perfectly suited for tracking.

If a user uploaded avatar is planned that will be also fine. My idea with the url was to not have the need for avatar storage but if you are fine with that, thats even better.

**Comment by rixx** [comment]
We're planning to cache Gravatar images to avoid privacy issues, it's just further down the roadmap. Definitely a point to keep in mind though, so thank you for bringing it up!
