### ISSUE TITLE
[Feature Request] Matrix Integration

### ISSUE THREAD

**Issue by lovelaced** [venueless/venueless#60]
Would be super cool if matrix could be integrated as chat here because then it could be bridged to any other platform. This maybe could help with #50 too(?) since technically the official matrix client supports etherpad integrations.

**Comment by rashfael** [comment]
Initially we actually wanted to base our chat on matrix. While the protocol is well documented, the reference server (synapse) sadly is not (we could not get it to integrate well with external auth).
A matrix bridge would be interesting, but is a lot of work and probably won't be happening anytime soon.

**Comment by lovelaced** [comment]
As a matrix admin I agree :). Maybe could be interesting to base chat on a bridgeable protocol (XMPP, IRC) instead; I guess this is more a suggestion/inquiry than a request.

**Comment by rixx** [comment]
If at all, this is a very long-term goal atm, I'm afraid. It's not so much that we're opposed to it, and more that the priority is very low.

**Comment by lovelaced** [comment]
Thanks, just thought I'd put it out there. :sparkles:
