### ISSUE TITLE
With a lot of entries, the structure of the menu get's a bit distracted (only Safari)

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#67]
Tested with recent Safari 13.1.1 (MacOS 15.5), in Chrome everything is fine. 

**Safari**
<img width="273" alt="Safari" src="https://user-images.githubusercontent.com/1153741/87167406-3286ca00-c2cd-11ea-8470-2c32559c3cd9.png">
**Chrome**
<img width="272" alt="Chrome" src="https://user-images.githubusercontent.com/1153741/87167400-31ee3380-c2cd-11ea-9725-fffc17675ac9.png">

**Comment by rixx** [comment]
Will be handled by #78
