### ISSUE TITLE
How to do video streaming ourselves

### ISSUE THREAD

**Issue by rashfael** [venueless/venueless#7]
Our video streaming needs are roughly divided into two needs:
1. 1:N streaming speaker -> viewers, with moderation and live mixing by organizers
2. N:M streaming aka group video chat

For those two needs, two different tech stacks exist, HLS/DASH and WebRTC (1:N streaming can be done via WebRTC but HLS/DASH scales way better).

Since we do not want and can not build that from the ground up, what are libaries / server that we can use?

Open source is pretty much required, since we are publish our own source and want people to host their own.

- https://openvidu.io/
- https://mediasoup.org/
- https://github.com/medooze
- https://github.com/NodeMedia/NodeMediaServer
- https://janus.conf.meetecho.com/ (https://www.meetecho.com/en/)
- https://antmedia.io/
- https://github.com/ossrs/srs
- https://github.com/Red5/red5-server
- https://github.com/voc

**Comment by raphaelm** [comment]
Closing since we're working on this and for now it looks like Janus is the way to go
