### ISSUE TITLE
[UX] Please don't hide main emojis in livestream view

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#72]
This is more a question of taste. I would like that the emojis for the livestream are more visible and don't get hidden. There is enough space for them in the bar and I don't get confused with the little greyed out emoji for the text-chat just next to it. 
I like this....
<img width="432" alt="Bildschirmfoto 2020-07-14 um 18 00 54" src="https://user-images.githubusercontent.com/1153741/87448599-56634c00-c5fc-11ea-8dc7-3a325b45e88d.png">

...more than that. 
<img width="151" alt="Bildschirmfoto 2020-07-14 um 18 00 59" src="https://user-images.githubusercontent.com/1153741/87448612-5b280000-c5fc-11ea-81ac-93168d1ed1ed.png">

**Comment by rashfael** [comment]
Thanks, that's already on our list of improvements. The expanding panel was originally part of a larger design, but right now there still is enough space for reactions being always expanded, since other features are not finished yet.
