### ISSUE TITLE
[Feature] Allow to link to rooms on the same domain within markdown texts

### ISSUE THREAD

**Issue by raphaelm** [venueless/venueless#74]
cc @robbi5

**Comment by rashfael** [comment]
Current component: https://github.com/venueless/venueless/blob/master/webapp/src/components/MarkdownPage.vue
We should replace `sanitizeHtml` with `markdown-it` functionality (allow only certain markdown rules).
We then can customize the link code to add a blank target only to urls starting with `http` or something.
We already have similar code here:
https://github.com/venueless/venueless/blob/d1aa28bced8334bf2c139957d168c449c61c6f79/webapp/src/components/ChatMessage.vue#L65-L69
