### ISSUE TITLE
Schedule data model, or: how mandatory is pretalx usage in venueless?

### ISSUE THREAD

**Issue by rixx** [venueless/venueless#80]
## RFC: How do we handle schedule data

Thoughts about handling schedule data in venueless events, particularly regarding more information about talks and speakers without increasing the burden of data transmission and avoidable polling. Let's discuss which direction we want to take with venueless, without getting tied up in implementation details too much.

### Status quo

Currently, we deliver all schedule data via a JSON blob (in a format that pretalx provides natively, but does not have to come from pretalx). The server knows nothing about the schedule itself, and only provides the JSON URL.

### Problem: Updates

This works, but has a problem with scoping and transmission sizes: Without server-knowledge, the frontend pulls this JSON blob regularly for updates, which racks up decent transmission sizes for bigger events. Currently, we only retrieve the minimal JSON file, which for a larger conference runs up to about 200kB.

### Problem: Lack of information

We are now starting to see that we also want detail pages for talks and speakers, and the JSON files containing that information can easily reach 1MB for a larger conference. Pulling 1MB every five minutes is not seem ideal. pretalx does provide an API to retrieve these details on-demand.

## Proposal 1: stronger pretalx integration

If we make stronger use of the existing pretalx API, we can do some neat things:

- Use the API to retrieve details as needed, thus offering detail pages/popovers for speakers and talks without huge transmission sizes.
- Receive a push on new schedule releases, leading to an announcement (#15) with the changed data included. This would remove the need for regular polling, making everybody much happier.

### Detail: Events without pretalx

My proposal would be to make a full pretalx integration optional, but optimise for that use case. Our current mode of operations can continue as-is, but if we assume that there is a pretalx integration, we can do way more awesome things, such as:

I'd propose to rename the `pretalx` field to `schedule_data` in the world config for events that don't use pretalx, so that it's clear which set of capabilities we support.

## Proposal 2: stronger schedule data model

The alternative would be to integrate the schedule into the backend, so that the backend can provide these kinds of information. That would require data models for talks, speakers, schedules, and m:n mappings between all of those.

I don't think that's fundamentally bad, but it'd duplicate parts of pretalx into venueless, and I'm not sure that we have the time/energy/focus for that, if it can be avoided.

**Comment by rashfael** [comment]
Since we have since done a lot of work regarding this topic, I'll close this issue, but feel free to reopen.
