### ISSUE TITLE
When (re-)opening a DM, but not writing anything, the channel does not persist and F5 breaks the UI

### ISSUE THREAD

**Issue by rashfael** [venueless/venueless#84]
Probably related to the "anti-ghost-open" DM feature.
Should the UI just drop to `/` when that happens or should we persist the channel for the opening user?

**Comment by raphaelm** [comment]
I'd consider this a backend bug since https://github.com/venueless/venueless/blob/master/server/venueless/core/services/chat.py#L263 already contains code to persist that channel for the opening user, it appearently does not work though :)
