### ISSUE TITLE
Menus in Safari are more like a tag cloud

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#98]
Well, of course, I really wanted to exaggerate by adding as many menus as there are different types of options, but... Chrome is fine, Safari is a bit of a mess. Guess which image belongs to which browser. 🤓

<img width="273" alt="Safari" src="https://user-images.githubusercontent.com/1153741/91494912-f11c9f00-e8b9-11ea-81df-aebab78c910a.png">
<img width="275" alt="Chrome" src="https://user-images.githubusercontent.com/1153741/91494917-f2e66280-e8b9-11ea-94e6-41646fcc88f1.png">

**Comment by rashfael** [comment]
Fixed, but please dial back the snark.
