### ISSUE TITLE
Hamburger menu makes more visible in the rooms but creates lots of clicking to switch between

### ISSUE THREAD

**Issue by saschafoerster** [venueless/venueless#99]
Especially when creating a new world every time you have to make many more clicks than before. I also get lost, because I am missing an overview, where I am. 

How about just a smaller menu, that is collapsible? ActiveCollab has a nice one: 
https://twitter.com/activecollab/status/1293486150120869888

**Comment by rashfael** [comment]
We already discussed a "mini" sidebar internally, but since venueless is still evolving at a fast pace, we don't want to nail down a complex design with many modes anytime soon.

**Comment by saschafoerster** [comment]
Hm, would it at least be possible to keep the menu open, when I opened it once? So I don't have to re-open after every single pageload? And keep it closed, when I closed it manually once?

**Comment by saschafoerster** [comment]
Again, I try to show someone around in our Venueless instance and it takes twice as many clicks and every time a new orientation, where I am. I wish back for the old behavior painfully much. Thanks for understanding and listening.

**Comment by raphaelm** [comment]
Can you tell us what device and display resolution you are using?

**Comment by saschafoerster** [comment]
MacOS/Safari.  Desktop is 1280px large when in fullscreen. Here is the behavior. I preferred a somewhat more stable menu that stays open when I am switching in between rooms and menus without closing every single time and then to be reopened manually. 
![Pretalx-Integration](https://user-images.githubusercontent.com/1153741/91904527-5ea74180-eca5-11ea-96d5-1d2e484dc729.gif)

**Comment by raphaelm** [comment]
We did understand what you're asking for, no worries or need to reiterate ;)

Our intention behind this change was that we think on 1280px the screen is too small to show e.g. video content and chat at a decent size while keeping the sidebar open. To be honest, I didn't even think desktop computers with 1280px screen width are still being made, we considered this to be a "tablet size", and quite frankly, on my iPad WITH a sidebar, the video became just a few centimetres small which wasn't really useful.

again: what device is this?

**Comment by saschafoerster** [comment]
MacBook Pro (15 inch, 2019), and well, I prefer bigger text it seems :) So Safari shows 1280px to me. Chrome as well (even though they have "Retina"-resolution.)
<img width="593" alt="Bildschirmfoto 2020-09-01 um 23 47 49" src="https://user-images.githubusercontent.com/1153741/91909474-8ef2de00-ecad-11ea-9c2c-3323a178e364.png">

**Comment by saschafoerster** [comment]
Alright, now, when I switch to standard, I can't read anything BUT the sidebar is back to the mode I prefer. Sorry for being a mole: didn't see that coming ... 🤓

**Comment by raphaelm** [comment]
Interesting. Obviously the perfect solution would be to provide a bigger font size while keeping the dimensions intact.

I see your point, but I still see the problem of the video being the main content and still being ridiculously small on e.g. an iPad.

I do not yet have a good idea on how to resolve this conflict of interest.

**Comment by saschafoerster** [comment]
For my part I switched to the scaled version just next to standard and I might get glasses :D
